# Generated by Django 5.2.4 on 2025-07-28 05:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('General Service', 'General Service'), ('Document Processing', 'Document Processing'), ('Payment', 'Payment'), ('Consultation', 'Consultation'), ('Technical Support', 'Technical Support')], max_length=50)),
                ('token_number', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('in-progress', 'In Progress'), ('completed', 'Completed')], default='waiting', max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
