# Generated by Django 5.2.4 on 2025-08-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_manager', '0004_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueentry',
            name='token_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
